// <auto-generated />
namespace presentacion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class modificacion1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modificacion1));
        
        string IMigrationMetadata.Id
        {
            get { return "202004230620078_modificacion1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
